#!/bin/bash
# Build warp/.env.warp from warp/wgcf-profile.conf (manual fallback).
#
# Use this when `wgcf register` is blocked on the VPS (datacenter IP):
# register + generate on a home machine, copy wgcf-profile.conf here,
# then run:  ./build-env-warp.sh
#
# Output format matches what register-warp.sh / wgcf-init writes,
# which is what wg-config.sh reads inside the container.
set -euo pipefail

PROFILE="${1:-warp/wgcf-profile.conf}"
OUT="warp/.env.warp"

if [ ! -f "$PROFILE" ]; then
    echo "ERROR: $PROFILE not found." >&2
    echo "Copy wgcf-profile.conf from your home machine first (see README step 2 fallback)." >&2
    exit 1
fi

getval() {
    sed -n "s/^$1[[:space:]]*=[[:space:]]*//p" "$PROFILE" | head -1
}

PRIVKEY="$(getval 'PrivateKey' | tr -d ' \r')"
PUBKEY="$(getval 'PublicKey' | tr -d ' \r')"
ADDRS="$(getval 'Address' | tr -d ' \r')"
ENDPOINT="$(getval 'Endpoint' | tr -d ' \r')"
ENDPOINT_HOST="${ENDPOINT%:*}"
ENDPOINT_PORT="${ENDPOINT##*:}"
ENDPOINT_HOST="$(printf '%s' "$ENDPOINT_HOST" | tr -d '[]')"

# Endpoint is usually engage.cloudflareclient.com — resolve to a literal IP
# (same as register-warp.sh). If resolution fails, keep the hostname:
# WireGuard itself can resolve it when the tunnel comes up.
RESOLVED=""
if command -v getent >/dev/null 2>&1; then
    RESOLVED="$(getent ahostsv4 "$ENDPOINT_HOST" 2>/dev/null | awk '{print $1}' | head -1 || true)"
fi
if [ -n "${RESOLVED:-}" ]; then
    ENDPOINT_HOST="$RESOLVED"
else
    echo "NOTE: could not resolve $ENDPOINT_HOST to an IP here — keeping the hostname." >&2
    echo "WireGuard will resolve it at tunnel setup. If wg-config fails, install" >&2
    echo "libc-bin (getent) or rerun this script on a host with DNS." >&2
fi

missing=0
for var in PRIVKEY PUBKEY ADDRS ENDPOINT_HOST ENDPOINT_PORT; do
    if [ -z "${!var:-}" ]; then
        echo "ERROR: could not parse ${var} from $PROFILE" >&2
        missing=1
    fi
done
if [ "$missing" -ne 0 ]; then
    echo "Is $PROFILE a real wgcf-profile.conf? It needs PrivateKey, Address," >&2
    echo "PublicKey and Endpoint lines." >&2
    exit 1
fi

mkdir -p warp
cat > "$OUT" <<EOF
# Generated by build-env-warp.sh from wgcf-profile.conf — do not hand-edit.
# (Manual path: VPS IP was blocked for wgcf register, profile made at home.)
WIREGUARD_ENDPOINT_IP=$ENDPOINT_HOST
WIREGUARD_ENDPOINT_PORT=$ENDPOINT_PORT
VPN_ENDPOINT_IP=$ENDPOINT_HOST
VPN_ENDPOINT_PORT=$ENDPOINT_PORT
WIREGUARD_PUBLIC_KEY=$PUBKEY
WIREGUARD_PRIVATE_KEY=$PRIVKEY
WIREGUARD_ADDRESSES=$ADDRS
EOF
chmod 600 "$OUT"

echo "Wrote $OUT:"
cat "$OUT"
echo ""
echo "OK — 7 lines, no empty values after '='. Continue with step 3."
