#!/bin/bash
set -euo pipefail

# Bring up the warp0 WireGuard (Cloudflare WARP) interface and install routing
# policy, so Tailscale's own traffic goes direct (real IP) while exit-node
# traffic goes through WARP.
#
# WARP credentials are generated by wgcf-init and mounted at /warp/.env.warp
# (fall back to WARP_* env vars if the file is absent).

if [ -f /warp/.env.warp ]; then
    set -a
    . /warp/.env.warp
    set +a
fi

WARP_PRIVATE_KEY="${WIREGUARD_PRIVATE_KEY:-${WARP_PRIVATE_KEY:-}}"
WARP_PUBLIC_KEY="${WIREGUARD_PUBLIC_KEY:-${WARP_PUBLIC_KEY:-}}"
WARP_ENDPOINT_IP="${WIREGUARD_ENDPOINT_IP:-${WARP_ENDPOINT_IP:-}}"
WARP_ENDPOINT_PORT="${WIREGUARD_ENDPOINT_PORT:-${WARP_ENDPOINT_PORT:-}}"
WARP_ADDRESS="${WIREGUARD_ADDRESSES%%,*}"   # IPv4 only (profile has v4 + v6)

for var in WARP_PRIVATE_KEY WARP_PUBLIC_KEY WARP_ENDPOINT_IP WARP_ENDPOINT_PORT WARP_ADDRESS; do
    if [ -z "${!var:-}" ]; then
        echo "ERROR: $var is not set (run wgcf-init once to generate warp/.env.warp)" >&2
        exit 1
    fi
done

# Cloudflare WARP is point-to-point (/32) — no gateway, route via the device.
TABLE=51820
FWMARK=51820
PRIORITY=6000

echo "Configuring warp0 WireGuard (Cloudflare WARP) interface..."

# Idempotent: drop any previous instance
ip link del warp0 2>/dev/null || true

ip link add warp0 type wireguard

# Apply WG config via a private temp file (private key never hits a world-readable path)
CONF=$(mktemp)
trap 'rm -f "$CONF"' EXIT
chmod 600 "$CONF"
cat > "$CONF" <<EOF
[Interface]
PrivateKey = ${WARP_PRIVATE_KEY}
FwMark = ${FWMARK}

[Peer]
PublicKey = ${WARP_PUBLIC_KEY}
AllowedIPs = 0.0.0.0/0
Endpoint = ${WARP_ENDPOINT_IP}:${WARP_ENDPOINT_PORT}
PersistentKeepalive = 25
EOF
wg setconf warp0 "$CONF"

ip addr add "${WARP_ADDRESS}" dev warp0
# Must match tailscale0's 1280 — a higher WARP MTU drops return-path packets
# (asymmetric loss / throughput cap).
ip link set warp0 mtu 1280
ip link set warp0 up

# Policy: any packet NOT marked by WG itself (FwMark=51820) goes through table 51820.
# WG's outgoing tunnel packets are marked, so they bypass the rule and use the main
# table → eth0 → WARP endpoint. Tailscale's own rules at priority 5210-5270
# are evaluated before ours (lower priority wins) and let control traffic go direct.
ip -4 rule del priority "${PRIORITY}" 2>/dev/null || true
ip -4 rule add not from all fwmark "${FWMARK}" table "${TABLE}" priority "${PRIORITY}"

ip -4 route replace default dev warp0 table "${TABLE}" metric 500

echo "warp0 up: address=${WARP_ADDRESS}, table=${TABLE}, fwmark=${FWMARK}"